import Head from "next/head";
// import Link from "next/link";
import { ConnectButton } from '@rainbow-me/rainbowkit';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen bg-gradient-to-b justify-end from-[#2e026d] to-[#15162c] ">
        <div className="m-2 fixed">
          <ConnectButton />
        </div>
      </main>
    </>
  );
}

